env:
  global:
    - secure: Csr0tKmx+8LQzwo2B8FLwKRDPZ+ae8rNEhgAVYZn8uDIqmVtc90EZJkKslnflUw6Mczwm8xTZjyH0ZHRMBYSmChtvjnRI3fha7dJAOb5tjIW/f1SOtoReXsXuws2J4EMkTkPIkmI/4+EXHL+2NzllVLQXJG0F3CDvaNRkH6kUeE=
install:
  - curl 'http://www.rust-lang.org/rustup.sh' | sudo sh
script:
  - make clean
  - make
  - make test
  - make doc
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
